//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_PRODAVNICA_NAKITAnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class kupovina_stavka
    {
        public int id { get; set; }
        public int KUPAC_kupac_id { get; set; }
        public int NAKIT_nakit_id { get; set; }
    
        public virtual kupac kupac { get; set; }
        public virtual nakit nakit { get; set; }
    }
}
